### PR TITLE
Some proposed changes

### PR DESCRIPTION
**Pull request by cgueret**
The propositions are split in different commits for easier picking among them ;-)

### CODE REVIEW

**Review by bernafarias — COMMENTED** [review]
1509848 I think this edition changes the semantics of the question. The BP should deal with something that is unique to the Web.

After some discussions, It's OK to make this change.

Updated by Berna's commit 5dcbac2189c375829d3df1cad6ce062849da6e5f

**Review by bernafarias — COMMENTED** [review]
e70fc2c  I used the http://www.geonames.org/3399415 and it worked. Is it really necessary to change?

e70fc2c After discussing this with Christophe, It's OK to change

Updated by Berna's commit 4dad5fa6b189ae77dac679ecc48131f2ca24a459

**Review by bernafarias — COMMENTED** [review]
9873c6b I think we should leave dct:publisher because this can also be seen as a descriptive metadata, no?
I agree with including dct:language.

After some discussions, It's OK to make this update, i.e. to remove dct:publisher and to include dct:language.

Updated by Berna's commit 5dcbac2189c375829d3df1cad6ce062849da6e5f

**Review by bernafarias — COMMENTED** [review]
bf13401 My suggestion:
Examples of the application of some Best Practices are shown using Turtle [[Turtle]] or JSON-LD [[JSON-LD]]

Christophe is OK with my suggestion. Update according to my suggestion.

**Review by bernafarias — DISMISSED** [review]

**Review by bernafarias — COMMENTED** [review]
28224c9  OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
3f93909 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
325afd5 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
0f5f29a  The idea in this case is that a machine can find the data license, but the data license itself doesn't need to be processable.

Christophe is OK with not updating. Leave the way that it is.

**Review by bernafarias — COMMENTED** [review]
28224c9  OK!

**Review by bernafarias — COMMENTED** [review]
5b3a63a OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
e221420  OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
60e9862  OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
3c3f77c OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
84e72f5 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
6578a4a OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
640599f OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
c08375c OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
82bd244 OK!
(cherry-picked) 🍒

**Review by bernafarias — COMMENTED** [review]
c7496c2  The example shows the inclusion of the locale parameters metadata, followed by a locale-neutral representation of bus fare data.  The example has to parts: one that shows that metadata and the other one to show an example of representation. I suggest to leave it like this.

SOLUTION: Let's split the code into two <pre>

**Review by bernafarias — COMMENTED** [review]
db17381  I think it is ok to leave axiom. There is also a reference to OWL2, so more details can be found there.

Christophe is OK with not updating. Leave the way that it is.

**Review by bernafarias — COMMENTED** [review]
41ec320 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
55d3c72 I agree. I think we should also include R-FormatMultiple.

Let's do the update suggested by Christophe and let's also include R-FormatMultiple.

**Review by bernafarias — COMMENTED** [review]
23fcd60 I'm ok with that, but I'm not a specialist :)
I agree :-)
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
d75ed12 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
7374375 I think if we change the first sentence to remove the reference to sensitive data, then it becomes more  generic and solves the problem.

Christophe is OK with not updating. Leave the way that it is.

**Review by bernafarias — COMMENTED** [review]
3e4f7ce OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
ba6dcd8 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
0c313df I think so. However, I think this update requires a major change on the BP. I suggest to leave the way it is.

Christophe is OK with not updating. Leave the way that it is.

**Review by bernafarias — COMMENTED** [review]
f1900c0 OK!
(cherry-picked)

**Review by bernafarias — COMMENTED** [review]
22d00c1 OK!

**Comment by cgueret** [comment]
Yep because you want the WoD identifier there. The www link gets you to the
 page in HTML and does not work for content negotiation:
curl -H "Accept: application/rdf+xml" -L -I http://www.geonames.org/3399415



On 25 November 2016 at 18:17, Bernadette F. Loscio <notifications@github.com

**Comment by bernafarias** [comment]
After some discussion, we agree to merge some of the proposed updates the way the were proposed. Other proposals were not considered and other ones were merged after small changes. Comments were added to the pull request explaining our decisions.

more details: https://lists.w3.org/Archives/Public/public-dwbp-comments/2016Dec/0003.html

**Pull request closed without merging**
